// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by gen_deps.go; DO NOT EDIT.

package integration

import (
	// And depend on a bunch of tailscaled innards, for Go's test caching.
	// Otherwise cmd/go never sees that we depend on these packages'
	// transitive deps when we run "go install tailscaled" in a child
	// process and can cache a prior success when a dependency changes.
	_ "github.com/metacubex/tailscale/chirp"
	_ "github.com/metacubex/tailscale/client/local"
	_ "github.com/metacubex/tailscale/cmd/tailscaled/childproc"
	_ "github.com/metacubex/tailscale/control/controlclient"
	_ "github.com/metacubex/tailscale/derp/derphttp"
	_ "github.com/metacubex/tailscale/drive/driveimpl"
	_ "github.com/metacubex/tailscale/envknob"
	_ "github.com/metacubex/tailscale/feature"
	_ "github.com/metacubex/tailscale/feature/buildfeatures"
	_ "github.com/metacubex/tailscale/feature/condregister"
	_ "github.com/metacubex/tailscale/feature/ssh"
	_ "github.com/metacubex/tailscale/health"
	_ "github.com/metacubex/tailscale/hostinfo"
	_ "github.com/metacubex/tailscale/ipn"
	_ "github.com/metacubex/tailscale/ipn/conffile"
	_ "github.com/metacubex/tailscale/ipn/ipnlocal"
	_ "github.com/metacubex/tailscale/ipn/ipnserver"
	_ "github.com/metacubex/tailscale/ipn/store"
	_ "github.com/metacubex/tailscale/ipn/store/mem"
	_ "github.com/metacubex/tailscale/logpolicy"
	_ "github.com/metacubex/tailscale/logtail"
	_ "github.com/metacubex/tailscale/net/dns"
	_ "github.com/metacubex/tailscale/net/dnsfallback"
	_ "github.com/metacubex/tailscale/net/netmon"
	_ "github.com/metacubex/tailscale/net/netns"
	_ "github.com/metacubex/tailscale/net/proxymux"
	_ "github.com/metacubex/tailscale/net/socks5"
	_ "github.com/metacubex/tailscale/net/tsdial"
	_ "github.com/metacubex/tailscale/net/tstun"
	_ "github.com/metacubex/tailscale/paths"
	_ "github.com/metacubex/tailscale/safesocket"
	_ "github.com/metacubex/tailscale/syncs"
	_ "github.com/metacubex/tailscale/tailcfg"
	_ "github.com/metacubex/tailscale/tsd"
	_ "github.com/metacubex/tailscale/tsweb/varz"
	_ "github.com/metacubex/tailscale/types/flagtype"
	_ "github.com/metacubex/tailscale/types/key"
	_ "github.com/metacubex/tailscale/types/logger"
	_ "github.com/metacubex/tailscale/types/logid"
	_ "github.com/metacubex/tailscale/util/clientmetric"
	_ "github.com/metacubex/tailscale/util/eventbus"
	_ "github.com/metacubex/tailscale/util/osshare"
	_ "github.com/metacubex/tailscale/util/syspolicy/pkey"
	_ "github.com/metacubex/tailscale/util/syspolicy/policyclient"
	_ "github.com/metacubex/tailscale/version"
	_ "github.com/metacubex/tailscale/version/distro"
	_ "github.com/metacubex/tailscale/wgengine"
	_ "github.com/metacubex/tailscale/wgengine/netstack"
	_ "github.com/metacubex/tailscale/wgengine/router"
)
